---
- name: Docker | Install APT dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-apt
    - apt-transport-https
    - ca-certificates

- name: Docker | Add apt key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- name: Docker | Add docker repos
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
    state: present

- name: Docker | Make sure docker and its dependencies are installed and started
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - docker-engine
  notify: restart docker

